### ISSUE TITLE
Don't stop the capture when the interface goes down due to sleep on Windows

### ISSUE THREAD

**Issue by jay** [the-tcpdump-group/libpcap#402] opened 2014-12-27 07:08 UTC
Hello and thank you for your work on libpcap. I am using Wireshark and I would like capture to continue automatically when I resume from sleep. I can't find a way to do it though. It seems either something in Wireshark or libpcap prevents that from happening because the capture is stopped.

I filed a [bug](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=10800) with Wireshark and the person who replied suggested I contact your group. Here is a copy of my report:

> Build Information:
> wireshark 1.12.2 (v1.12.2-0-g898fa22 from master-1.12)
> 
> Compiled (64-bit) with GTK+ 2.24.23, with Cairo 1.10.2, with Pango 1.34.0, with
> GLib 2.38.0, with WinPcap (4_1_3), with libz 1.2.5, with SMI 0.4.8, with c-ares
> 1.9.1, with Lua 5.2, without Python, with GnuTLS 3.2.15, with Gcrypt 1.6.2,
> without Kerberos, with GeoIP, with PortAudio V19-devel (built Nov 12 2014), with
> AirPcap.
> 
> Running on 64-bit Windows 7 Service Pack 1, build 7601, with WinPcap version
> 4.1.3 (packet.dll version 4.1.0.2980), based on libpcap version 1.0 branch
> 1_0_rel0b (20091008), GnuTLS 3.2.15, Gcrypt 1.6.2, without AirPcap.
> 
> Built using Microsoft Visual C++ 10.0 build 40219
> ## 
> 
> When I am monitoring a network with wireshark and my computer goes to sleep, on resume the capture has stopped. I get an error "The network adapter on which the capture was being done is no longer running; the capture has stopped."
> 
> Feature request: Please offer a way to ignore a downed interface so if the interface goes down and comes back up again Wireshark will automatically resume capture.
> 
> Thanks

**Comment by Hi-Angel** [comment] 2019-09-26 07:56
Just stumbled upon it: the problem is even more serious than it seems, because I'm getting this error every time I run `dhcpdump -i wlp2s0` for my wifi card, and start connection. I am not doing suspend or anything, and the interface name doesn't change. This means that for some cards libpcap functional is limited.

**Comment by bamartin125** [comment] 2019-10-09 02:49
It looks like @yuguy had the right idea about this in 2008 through this commit:
https://github.com/the-tcpdump-group/libpcap/commit/34624f128f2e6f937c04317fdd2c0ae6d8883ad5#diff-72e0c84412cdb9e7102d6243c3880508R683

This commit would have probably allowed the packet capture through an interface down event as the conditional would have ignored `ENETDOWN`. In fact, the change that @yuguy made is still documented in the comments that were added.

But then in 2009, @guyharris made a change to the do-while conditional in this commit:
https://github.com/the-tcpdump-group/libpcap/commit/e9de4b862ed18e08b9d1d8f04c804bed30a51431#diff-72e0c84412cdb9e7102d6243c3880508R1352

@guyharris was probably just trying to add a print when the interface went down. In doing so, he also made the loop break and thus the functionality made by @yuguy was broken.

Even though this functionality changed, the comment made by @yuguy was not modified by @guyharris.

The current behavior will not ignore an `ENETDOWN`. I would be in favor of trying to merge the functionalities that were intended in each of these commits by moving the print functionality into the while loop and not return `PCAP_ERROR` at that point.

**Comment by bamartin125** [comment] 2019-10-09 03:36
I fiddled with this and found out that with my hardware, I was seeing the code break out of the loop from this block:
https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-linux.c#L5139-L5151

By adding a `continue` statement at the end of this block, I was able to keep libpcap and thus tcpdump from terminating when the interface goes down.

**Comment by bamartin125** [comment] 2019-10-09 04:20
I just made this pull request:
https://github.com/the-tcpdump-group/libpcap/pull/858

**Comment by guyharris** [comment] 2019-10-10 03:21
The original problem was on Windows.  That was fixed by changes to the Npcap kernel code, which is where the problem was.

The second report was for Linux, which is a separate issue involving a completely separate code path.  Simply adding a continue statement helps with the issue reported, but means that if an interface *completely goes away* during capture - e.g., unplugging a USB adapter - the capture *doesn't* stop (and plugging it back in again won't resume the capture, because the new interface isn't bound to the PF_PACKET socket on which the capture was being done).

I think there's a way to distinguish between "interface went down but is still present" from "interface disappeared", but it's not simple because the ENETDOWN is delivered before the interface is completely removed to the point that an SIOCGIFINDEX given the adapter name either fails or succeeds with a new ifindex.  I put my change to do that aside because I had other things dumped onto my plate, so I'll need to page-fault back the context of what the issues were before resuming work.

**Comment by guyharris** [comment] 2019-10-10 03:23
OK, the *Windows* issue is fixed.  If you want the *Linux* issue to remain open, please open it as a separate issue (with "Linux" in the title, as it's not an issue on *BSD or, I think macOS, for example - they just let the capture continue; they only deliver an indication if the interface goes away).

**Closed by guyharris** 2019-10-10 03:23 UTC
Labels: feature request

**Comment by guyharris** [comment] 2019-10-10 03:43
> The original problem was on Windows. That was fixed by changes to the Npcap kernel code, which is where the problem was.

See nmap/nmap/#1650

**Comment by bamartin125** [comment] 2019-10-10 04:12
Thanks so much @guyharris for taking care of this so quickly. I cannot test/evaluate the Windows version of this code, but your comments and code changes better help me to understand the nuances that I was not understanding at all when I first started looking at this issue.

I'd like to see if I can help with the Linux version of this issue which I just opened.
