### ISSUE TITLE
CAP_NET_RAW is not enough with kernel 4.15

### ISSUE THREAD

**Issue by lufik** [the-tcpdump-group/libpcap#689] opened 2018-04-13 07:58 UTC
I have a problem with Ubuntu 16.04. I gave capability CAP_NET_RAW to tcpdump binary and it was able to sniff traffic on all interfaces (I need immediate mode). Once I upgraded kernel to version 4.15 it stopped working for USB network (it does not support offloading) with error message:

tcpdump: WARNING: enp0s20u6: SIOCETHTOOL(ETHTOOL_GUFO) ioctl failed: Operation not permitted
Warning: Kernel filter failed: Bad file descriptor
tcpdump: can't remove kernel filter: Bad file descriptor

However it sitll works with onboard interface (eno1) as it supports offloading and it never
ask for ETHTOOL_GUFO (this is not permitted now).

To be honest I don't see a reason to fail when offloading questions (in iface_get_offload don't have enough permission). From my point of view it's enough to expect worse scenario and continue. It is in create_ring (case TPACKET_V2). It's enough to comment out the part:
                        if (offload == -1) {
                                *status = PCAP_ERROR;
                                return -1;
                        }
and it works perfectly for all interfaces now.

Is it good idea or do I miss something? I can prepare pull request but I'm not 100% sure if it is good idea.

I take a look it's still the same in git master.

**Comment by infrastation** [comment] 2018-07-24 09:33
I have Ubuntu 18.04, which has kernel 4.15, on a computer with a PCI Intel NIC, which might support some kinds of offloading (cannot check now), and a USB Realtek NIC, which also has some offloading. If you tell exactly which kind of offloading makes the difference, and how to reproduce the problem, I can post my test results.

**Comment by lufik** [comment] 2018-08-07 20:32
I was on vacation. I'll check it once again tomorrow as I don't have the USB NIC here.

The test case was very simple:

1. Set the CAP_NET_RAW to tcpdump binary as root (`setcap CAP_NET_RAW+eip /usr/sbin/tcpdump`)
1. Run the tcpdump as ordinary user (`tcpdump -i <interface>`):
- it fails with some (USB) NIC without `ETHTOOL_GUFO` support
- it doesn't fail with NIC with `ETHTOOL_GUFO` support

**Comment by guyharris** [comment] 2018-08-07 23:38
> However it sitll works with onboard interface (eno1) as it supports offloading and it never
ask for ETHTOOL_GUFO (this is not permitted now).

It's not that it's not *permitted*, it's that it isn't *supported*; unfortunately, the 4.17.10 version of `dev_ethtool()` doesn't include `ETHTOOL_GUFO` in the "Allow some commands to be done by anyone" list, so the failure mode is that it fails with `EPERM` rather than with `EOPNOTSUPP` as it should (to indicate what the *real* problem is).

So if the other calls succeeded, meaning "we have enough permission to do the "Allow some commands to be done by anyone" stuff", we should treat an error of `EPERM` for `ETHTOOL_GUFO` as really meaning `EOPNOTSUPP`.

**Comment by guyharris** [comment] 2018-08-08 03:03
What a crock!

In the best of all possible worlds, there would be an ioctl that could be used to ask the kernel "on this `PF_PACKET` socket, what's the largest packet I will *ever* see?"  (No, this is not the MTU, as the packet size includes the link-layer header; it's not even calculable from the MTU, because of offloading, which can cause faked-up huge packets to be delivered, which is why we're doing all this "are we offloading?" nonsense.)

And this isn't even the second-best of all possible worlds, as there isn't a simple way of asking "are we doing any of those types of offloading?".

So I threw in a hack to treat `EPERM` as meaning `EOPNOTSUPP` for `ETHTOOL_GUFO`.  It's checked into the master branch, and I'll backport it to the 1.9 branch once it shows up on the main server for that branch (which isn't the GitHub server).

**Closed by guyharris** 2018-08-08 03:03 UTC

**Comment by guyharris** [comment] 2018-08-08 04:27
BTW, why is it using the TPACKET_V2 code?  Your kernel should support TPACKET_V3, which wouldn't have that issue (and would also drop fewer packets); what version of libpcap is tcpdump using?

**Comment by mcr** [comment] 2018-08-08 15:50
Guy Harris <notifications@github.com> wrote:
    > So I threw in a hack to treat EPERM as meaning EOPNOTSUPP for
    > ETHTOOL_GUFO. It's checked into the master branch, and I'll backport
    > it to the 1.9 branch once it shows up on the main server for that
    > branch (which isn't the GitHub server).

Should occur daily. Is it taking longer?

**Comment by fxlb** [comment] 2018-08-08 16:17
No, it is present now.

**Comment by guyharris** [comment] 2018-08-08 17:33
> As far as I remember V3 code is used in tcpdump

Tcpdump doesn't directly control whether V2 or V3 code is used.

> only for files

Neither V2 nor V3 nor V1 nor "don't use memory-mapped capture at all" is used for files; when reading a file, `pcap-linux.c` isn't involved at all.

> (not interfaces)

For interfaces, newer versions of tcpdump use immediate mode *if* tcpdump is printing to the console rather than writing to a file, and immediate mode currently uses V2 code.

Tcpdump should probably just use a smaller timeout, rather than immediate mode, and immediate mode should probably disable memory-mapped capturing completely rather than fall back on V2 code.

**Comment by guyharris** [comment] 2018-08-08 17:35
> Should occur daily. Is it taking longer?

No, but "daily" is slower than "as soon as it's checked into master".  At what time does the daily propagation from GitHub to bpf.tcpdump.org occur?

**Comment by guyharris** [comment] 2018-08-08 17:36
> No, it is present now.

I just propagated the change to the 1.9 branch.

**Comment by mcr** [comment] 2018-08-08 22:00
Guy Harris <notifications@github.com> wrote:
    >> Should occur daily. Is it taking longer?

    > No, but "daily" is slower than "as soon as it's checked into master".
    > At what time does the daily propagation from GitHub to bpf.tcpdump.org
    > occur?

1:23am daily.

**Comment by guyharris** [comment] 2018-08-08 22:06
> 1:23am daily.

UTC, Eastern time, or something else?

**Comment by mcr** [comment] 2018-08-09 01:19
Guy Harris <notifications@github.com> wrote:
    > 1:23am daily.
    > UTC, Eastern time, or something else?

EST.

**Comment by guyharris** [comment] 2018-08-09 01:27
> EST.

So 2:23 AM when daylight savings time/summer time is in effect?

Or 1:23 AM EST when it's not in effect and 1:23 EDT when it is?

**Comment by infrastation** [comment] 2018-08-09 07:49
If the cron job runs hourly, it will put the time zones out of scope.

**Comment by guyharris** [comment] 2018-08-09 08:51
> If the cron job runs hourly, it will put the time zones out of scope.

All I really want to know is "what time will it be in California when the changes make it to bpf.tcpdump.org", so I know whether it'll happen when I'm still awake or whether I need to cherry-pick the change the next morning. :-)

**Comment by mcr** [comment] 2018-08-09 14:11
Guy Harris <notifications@github.com> wrote:
    > All I really want to know is "what time will it be in California when
    > the changes make it to bpf.tcpdump.org", so I know whether it'll

It will be Miller Time?  :-)

The next morning, it should be sync'ed.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [
