### ISSUE TITLE
PCAP Append functionallity

### ISSUE THREAD

**Issue by overnine** [the-tcpdump-group/libpcap#409] opened 2015-01-25 16:09 UTC
Hey, I was looking for a way to append data to existing pcaps, and was amazed that this functionallity didn't exist. I see that it has even been discussed before, and it seemed like you all got to an agreement that it was a good idea, so I'm wondering why this was never merged into libpcap: http://seclists.org/tcpdump/2011/q2/153

**Comment by guyharris** [comment] 2015-01-25 23:27
Duplicate of #247.

**Closed by guyharris** 2015-01-25 23:27 UTC
Labels: duplicate
