### ISSUE TITLE
Does libpcap support writing pcapng format?

### ISSUE THREAD

**Issue by shifraepshtein** [the-tcpdump-group/libpcap#1304] opened 2024-03-27 09:00 UTC
Does libpcap support writing pcapng format?
If yes:
From which version it is supported?
Does it support also writing interface_name as option block (code = 2) under "Interface Description Block"?

**Comment by guyharris** [comment] 2024-03-27 09:39
> Does libpcap support writing pcapng format?

Not currently.

**Comment by guyharris** [comment] 2024-05-16 16:20
Duplicate of #1321

**Closed** 2024-05-16 16:20 UTC
Labels: pcapng
