### ISSUE TITLE
Unaligned Load Word: pid=426 (tcpdump), tid=100040, pc=0x40569034, badvaddr=0x4051d02a

### ISSUE THREAD

**Issue by cschuber** [the-tcpdump-group/libpcap#927] opened 2020-05-04 21:57 UTC
On FreeBSD:
* hostapd + wpa encryption + mips32 (mips74k in this instance) failson -HEAD.

* l2_packet_freebsd.c in hostapd uses a pcap filter to filter out eapol frames from other parties to the eapol/raw receive socket;
* the filter compilation causes an unaligned access on mips, which i /thought/ we handled correctly, but apparently not;
* the filter as written in hostapd doesn't result in anything being received.

The unaligned warn is:

Unaligned Load Word: pid=426 (tcpdump), tid=100040, pc=0x40569034,
badvaddr=0x4051d02a

(I dno't yet have the line of code, that's next too.)

The filter is:

*** Filter is "not ether src c4:6e:1f:5b:04:f7 and ( ether dst c4:6e:1f:5b:04:f7 or ether dst 01:80:c2:00:00:03 ) and ether proto 0x888e"

I'll try to get the MIPS user to supply more information.

**Comment by guyharris** [comment] 2020-05-05 03:36
> the filter compilation causes an unaligned access on mips

By "the filter compilation" do you mean 1) "the process of the filter being compiled into BPF code by `pcap_compile()`" or 2) "the process of the resulting BPF code being interpreted by a BPF interpreter, translated to machine code by a BPF JIT, or executed as machine code as generated by that JIT"?

**Comment by cschuber** [comment] 2020-05-05 12:43
I think what he means is tcpdump -i if0 "not ether src c4:6e:1f:5b:04:f7 and ( ether dst c4:6e:1f:5b:04:f7 or ether dst 01:80:c2:00:00:03 ) and ether proto 0x888e"

I'm still waiting for more information. Again, this is only on MIPS.

**Comment by guyharris** [comment] 2020-05-05 18:29
> I think what he means is tcpdump -i if0 "not ether src c4:6e:1f:5b:04:f7 and ( ether dst c4:6e:1f:5b:04:f7 or ether dst 01:80:c2:00:00:03 ) and ether proto 0x888e"

OK, that's a live capture, and it's a simple instruction, so the BPF code should either 1) be interpreted in the kernel or 2) JITted in the kernel (if FreeBSD has a JIT that compels BPF code to MIPS code).

So does he mean

1. it gets an unaligned load warning (I assume that FreeBSD is catching the trap, printing the warning, simulating the unaligned load, and continuing) when compiling that filter in libpcap's `pcap_compile()`;

1. it gets an unaligned load warning in the kernel BPF interpreter when executing the code generated by libpcap's `pcap_compile()`;

1. it gets an unaligned load warning in *tcpdump* when it's dissecting the packets?

If the answer is the third one, that's a *tcpdump* bug, not a *libpcap* bug.

**Comment by infrastation** [comment] 2020-08-13 23:26
@cschuber, is it OK to close this request because the additional information is not available?

**Comment by infrastation** [comment] 2020-08-28 20:24
Closing for now, you are welcome to reopen when you can provide the requested particulars and the steps to reproduce the problem.

**Closed by infrastation** 2020-08-28 20:24 UTC
Labels: waiting-for-more-information
