### ISSUE TITLE
VLAN Not Showing on Filter for VMXNET3 OK for E1000

### ISSUE THREAD

**Issue by hdiggens** [the-tcpdump-group/libpcap#473] opened 2016-01-08 19:04 UTC
Hi 
I have a 2 nics configured on a VMware Guest.
They are both connected to the same switch port group.

Centos
Linux X 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

TCPDUMP/LIBCAP Version
tcpdump-4.0.0-3.20090921gitdf3cb4.1.el6.i686
libcap-2.16-5.5.el6.i686

Eth1 is a VMXNET3 driver.
Eth2 is a E1000 driver.
###### 

[root@X ~]# ethtool -i eth1
driver: vmxnet3
version: 1.3.3.0-NAPI
firmware-version: N/A
bus-info: 0000:0b:00.0
###### 

[root@X ~]# ethtool -i eth2
driver: e1000
version: 7.3.21-k8-NAPI
firmware-version:
bus-info: 0000:02:01.0
###### 

Using the command "tcpdump -i eth? -c 5 vlan 265"
Works on the E1000 but not on the VMXNET3.
###### 

tcpdump -nne -i eth1 show I have the VLAN tags.
###### 

tcpdump -nne -i eth1 -c 5

tcpdump: WARNING: eth1: no IPv4 address assigned
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth1, link-type EN10MB (Ethernet), capture size 65535 bytes
13:25:08.791239 00:0c:29:17:25:25 > 28:92:4a:d3:04:8c, ethertype 802.1Q (0x8100), length 110: vlan 265, p 0, ethertype IPv4, 192.168.65.45.22 > 192.168.65.100.62887: Flags [P.], seq 3074575762:3074575814, ack 134309044, win 219, length 52
13:25:08.791250 00:0c:29:17:25:25 > 28:92:4a:d3:04:8c, ethertype 802.1Q (0x8100), length 110: vlan 265, p 0, ethertype IPv4, 192.168.65.45.22 > 192.168.65.100.62887: Flags [P.], seq 0:52, ack 1, win 219, length 52
13:25:08.792010 00:0c:29:17:25:25 > 28:92:4a:d3:04:8c, ethertype 802.1Q (0x8100), length 238: vlan 265, p 0, ethertype IPv4, 192.168.65.45.22 > 192.168.65.100.62887: Flags [P.], seq 52:232, ack 1, win 219, length 180
13:25:08.792018 00:0c:29:17:25:25 > 28:92:4a:d3:04:8c, ethertype 802.1Q (0x8100), length 238: vlan 265, p 0, ethertype IPv4, 192.168.65.45.22 > 192.168.65.100.62887: Flags [P.], seq 52:232, ack 1, win 219, length 180
13:25:08.792447 28:92:4a:d3:04:8c > 00:0c:29:17:25:25, ethertype 802.1Q (0x8100), length 64: vlan 265, p 0, ethertype IPv4, 192.168.65.100.62887 > 192.168.65.45.22: Flags [.], ack 232, win 251, length 0
5 packets captured
6 packets received by filter
0 packets dropped by kernel
###### 

[root@X ~]# tcpdump -i eth2 -c 5 vlan 265

tcpdump: WARNING: eth2: no IPv4 address assigned
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth2, link-type EN10MB (Ethernet), capture size 65535 bytes
13:21:41.974772 IP usflli-vct03.naclab.net.ssh > dexdemo.naclab.net.62887: Flags [P.], seq 3074572930:3074573014, ack 134305084, win 219, length 84
13:21:41.974776 IP usflli-vct03.naclab.net.ssh > dexdemo.naclab.net.62887: Flags [P.], seq 0:84, ack 1, win 219, length 84
13:21:41.981525 IP usflli-vct03.naclab.net.54733 > 192.168.64.5.domain: 5390+ [1au] PTR? 100.65.168.192.in-addr.arpa. (56)
13:21:41.981529 IP usflli-vct03.naclab.net.ssh > dexdemo.naclab.net.62887: Flags [P.], seq 84:248, ack 1, win 219, length 164
13:21:41.981530 IP usflli-vct03.naclab.net.ssh > dexdemo.naclab.net.62887: Flags [P.], seq 84:248, ack 1, win 219, length 164
5 packets captured
17 packets received by filter
0 packets dropped by kernel
###### 

[root@X ~]# tcpdump -i eth1 -c 5 vlan 265

tcpdump: WARNING: eth1: no IPv4 address assigned
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth1, link-type EN10MB (Ethernet), capture size 65535 bytes
^C
0 packets captured
14 packets received by filter
0 packets dropped by kernel
###### 

Any help/direction would be appreciated.

Harry

**Comment by infrastation** [comment] 2016-05-24 13:29
tcpdump 4.0.0 was released in 2008. Could you retry with the most recent builds of both libpcap and tcpdump git master branch and update if the issue still reproduces?

**Comment by infrastation** [comment] 2021-11-22 20:10
Closing due to lack of feedback.

**Closed by infrastation** 2021-11-22 20:10 UTC
Labels: runtime, Linux VLAN
