### ISSUE TITLE
memory allocation errors with larger filters

### ISSUE THREAD

**Issue by VVelox** [the-tcpdump-group/libpcap#1089] opened 2022-02-03 18:21 UTC
Been running into the issue with tcpdump and other items using libpcap in our environment. Found anything trying to load a larger BPF on debian10 or newer fails with a memory allocation error.

Testing with the newest kernel, libpcap, and tcpdump and I am still seeing the issue. I've included the error and other relevant bits below.

If anything else would be of assistance, please let me know.

Versions...
```
tcpdump version 5.0.0-PRE-GIT
libpcap version 1.11.0-PRE-GIT (with TPACKET_V3)
OpenSSL 1.1.1k  25 Mar 2021

kernel: 5.17.0-rc2+
```

Error...
```
[root@debian11-1]/root/tcpdump>./tcpdump -F ../bpf_test -i enp0s6
Warning: Kernel filter failed: Cannot allocate memory
```

example BPF...
```
not ( host 1.1.1.1 and port 514 ) and
not ( host 1.1.1.1 and port 1514 ) and
not ( host 1.1.1.1 and port 2514 ) and
not ( host 1.1.1.1 and port 3514 ) and
not ( host 1.1.1.1 and port 4514 ) and
not ( host 1.1.1.1 and port 5514 ) and
not ( host 1.1.1.1 and port 6514 ) and
not ( host 1.1.1.1 and port 7514 ) and
not ( host 1.1.1.1 and port 8514 ) and
not ( host 1.1.1.1 and port 9514 ) and
not ( host 1.1.1.2 and port 514 ) and
not ( host 1.1.1.2 and port 1514 ) and
not ( host 1.1.1.2 and port 2514 ) and
not ( host 1.1.1.2 and port 3514 ) and
not ( host 1.1.1.2 and port 4514 ) and
not ( host 1.1.1.2 and port 5514 ) and
not ( host 1.1.1.2 and port 6514 ) and
not ( host 1.1.1.2 and port 7514 ) and
not ( host 1.1.1.2 and port 8514 ) and
not ( host 1.1.1.2 and port 9514 ) and
not ( host 1.1.1.3 and port 514 ) and
not ( host 1.1.1.3 and port 1514 ) and
not ( host 1.1.1.3 and port 2514 ) and
not ( host 1.1.1.3 and port 3514 ) and
not ( host 1.1.1.3 and port 4514 ) and
not ( host 1.1.1.3 and port 5514 ) and
not ( host 1.1.1.3 and port 6514 ) and
not ( host 1.1.1.3 and port 7514 ) and
not ( host 1.1.1.3 and port 8514 ) and
not ( host 1.1.1.3 and port 9514 ) and
not ( host 1.1.1.4 and port 514 ) and
not ( host 1.1.1.4 and port 1514 ) and
not ( host 1.1.1.4 and port 2514 ) and
not ( host 1.1.1.4 and port 3514 ) and
not ( host 1.1.1.4 and port 4514 ) and
not ( host 1.1.1.4 and port 5514 ) and
not ( host 1.1.1.4 and port 6514 ) and
not ( host 1.1.1.4 and port 7514 ) and
not ( host 1.1.1.4 and port 8514 ) and
not ( host 1.1.1.4 and port 9514 ) and



not port 3260

```

**Comment by infrastation** [comment] 2022-02-03 22:43
For reference, the error does not reproduce on Ubuntu 20.04 with [HWE] kernel 5.13. Debian 11 currently uses kernel 5.10 (did not test). You are using your own build of the kernel, correct?

**Comment by VVelox** [comment] 2022-02-03 23:00
> For reference, the error does not reproduce on Ubuntu 20.04 with [HWE] kernel 5.13. Debian 11 currently uses kernel 5.10 (did not test). You are using your own build of the kernel, correct?

Tested with 5.17.0-rc2+ and the default kernel for Debian 10 and Debian 11.

Firing up a VM to test Ubuntu 20.04.

**Comment by VVelox** [comment] 2022-02-04 01:06
> For reference, the error does not reproduce on Ubuntu 20.04 with [HWE] kernel 5.13. Debian 11 currently uses kernel 5.10 (did not test). You are using your own build of the kernel, correct?

```
root@user:~# tcpdump -F bpf -i enp0s5 > /dev/null 
Warning: Kernel filter failed: Cannot allocate memory
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp0s5, link-type EN10MB (Ethernet), capture size 262144 bytes
^C0 packets captured
13 packets received by filter
0 packets dropped by kernel
root@user:~# uname -a
Linux user 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

It fails here on Ubuntu 20.04 Server as well. Be sure to check at the very top of the output for it. Catting to /dev/null should make it easily visible.

**Comment by infrastation** [comment] 2022-02-04 02:00
I stand corrected, it does reproduce as described. Excuse me, my presumption was that "fails" means tcpdump immediately exits with an error, in fact it continues to run after the message.

**Comment by VVelox** [comment] 2022-02-04 02:20
Aye. Tcpdump continues to run. Many others like suricata and daemonlogger, which also use libpcap, crash completely when that error is thrown.

**Comment by guyharris** [comment] 2022-02-04 21:28
Perhaps the meaning of the message would be clearer if it were

    Warning: Filter program requires too much memory in the kernel

The example given compiles to 675 instructions (with the libpcap that comes with macOS 12.2, but it's probably going to be similar on all other platforms.

On Linux, each socket has a count of the number of bytes of "other" or "option" memory associated with it; socket filters count against that.  The maximum amount of "other" memory that can be allocated per socket is 20480 bytes on a 64-bit platform.

That *should* be sufficient* for 675*8 = 5400 bytes of BPF program, but there may be other memory allocated for the socket as well, so that may have put the socket over the top.

I'll modify the code to improve the error message for ENOMEM, including adding the amount of memory currently allocated for the socket and the maximum amount of memory allowed to be allocated per socket.

**Comment by guyharris** [comment] 2022-02-04 21:32
> Tcpdump continues to run.

Yes - libpcap just prints the message and then does the filtering in user mode, which doesn't impose size limitations on the filter program.  That means that *all* packets are stored in the kernel buffer and provided to libpcap, which increases the CPU requirement and makes it more likely that the kernel buffer could fill up and cause the capture to drop packets, but that's life.

> Many others like suricata and daemonlogger, which also use libpcap, crash completely when that error is thrown.

It's not an error, it's just a warning message printed to the standard error.

If those programs crash, we'd need to see stack traces of the crash to see whether it's a libpcap bug or a bug in the program.

**Comment by guyharris** [comment] 2022-02-04 22:46
The message I get when I improve the error message is

    Warning: Couldn't allocate kernel memory for filter: current optmem 0, maximum optmem 20480

so it looks as if the filter's too complicated (meaning too big) for the kernel.  It's 5400 bytes, as generated by libpcap, so the problem must be somewhere else.

**Comment by VVelox** [comment] 2022-02-04 22:54
Actually bumping net.core.optmem_max does fix it.

```
[root@debian11-1]/root>sysctl net.core.optmem_max=204800           
net.core.optmem_max = 204800
[root@debian11-1]/root>tcpdump -F bpf_test -i enp0s6 > /dev/null   
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on enp0s6, link-type EN10MB (Ethernet), snapshot length 262144 bytes
^C23 packets captured
24 packets received by filter
0 packets dropped by kernel
[root@debian11-1]/root>
```

**Comment by guyharris** [comment] 2022-02-04 23:21
> Actually bumping net.core.optmem_max does fix it.

Yes, if you raise the limit sufficiently, you don't hit the limit.

The test filter in question apparently consumes 33640 bytes worth of "option/other memory" according to some debugging code I threw in.  Perhaps that's the machine-code output of the BPF JIT compiler.

**Comment by guyharris** [comment] 2022-02-05 01:27
If daemonlogger is the one at https://talosintelligence.com/daemon, then I can't reproduce the crash with the filter in question:

```
ubu20-04$ sudo ./daemonlogger -f /tmp/bpf_test -i ens33 -l /tmp
[-] Reading BPF filter in from file /tmp/bpf_test
[-] Interface set to ens33
[-] Logpath set to /tmp
[-] Log filename set to "daemonlogger.pcap"
[-] Pidfile configured to "daemonlogger.pid"
[-] Pidpath configured to "/var/run"
[-] Rollover size set to 18446744071562067968 bytes
[-] Rollover time configured for 0 seconds
[-] Pruning behavior set to oldest IN DIRECTORY

-*> DaemonLogger <*-
Version 1.2.1
By Martin Roesch
(C) Copyright 2006-2007 Sourcefire Inc., All rights reserved

Checking partition stats for log directory "/tmp/."
sniffing on interface ens33
Warning: Kernel filter failed: Cannot allocate memory
Logging packets to /tmp/daemonlogger.pcap.1644020084
^CQuitting!
```

so there's nothing more we can do here to fix the crashes, as we don't know what code is crashing.

**Comment by VVelox** [comment] 2022-02-10 22:04
Aye! That is correct. Looked like it was erroring, but was just bumping into a kernel limit that just needed raised.

**Comment by infrastation** [comment] 2022-02-11 12:07
Alright, let's close it as resolved then.

**Closed by infrastation** 2022-02-11 12:07 UTC
Labels: runtime, BPF related, linux
