### ISSUE TITLE
Is it possible to open a mmap .pcap file?

### ISSUE THREAD

**Issue by supersonicnumbers** [the-tcpdump-group/libpcap#1004] opened 2021-04-06 09:43 UTC
Hi,

I am working with very large files (+100G) and would like to be able to read them through pcap_open_with_tstamp_precision, however I would like to be able to mmap the file for increased speed, but when I do so I keep getting an error when trying to cast a char* to a FILE* in the aforementioned function.
Is there a way to parse through mmap files that I am missing?
I tried to have a look at the source code, but I am not able to find such an option, and hence assume it would require its own function. Please correct me if I am wrong.

Thank you!

**Comment by guyharris** [comment] 2021-04-06 10:19
> Is there a way to parse through mmap files that I am missing?

No.  Changing libpcap to use memory-mapping would require significant changes to sf-pcap.c and sf-pcapng.c; you would have to replace all code that read from the file using calls that take a `FILE *` as an argument with code that directly fetches the data from (mapped) memory.

**Comment by supersonicnumbers** [comment] 2021-04-06 10:35
I see, thanks.

Do you have any suggestion for my use case?

On a different note I could probably work on a patch that would address this (add mmap functionality) if it was of interest to the maintainers.

**Comment by supersonicnumbers** [comment] 2021-04-06 14:56
Hi Michael,

`Do you need to seek forward and backward in the file?
Do you need to collect packets into streams to form flows? I.e. keep some packets around while skipping forward to find more packets?
Aside from the size, are there other issues you are dealing with?`

The answer is _no_ to all  the questions. 

`We couldn't abandon the FILE* interface, because it's the most portable, and I don't think mmap(2) works at all the same way on windows.`

Totally agree and understand, however when dealing with large files it really makes sense to be able to mmap them, hence the new API you mentioned could really make the library cleaner and at the same time more powerful - it also doesn't seem like much work to add such functionality for at least `.pcap`files.

**Comment by mcr** [comment] 2021-04-06 15:02
If you are going to process the file sequentially, why does mmap(2) help?  The traditional kernel read-ahead buffering and FILE buffering should be very good (with 50 years of jurisprudence here), and some stdio(3) use mmap() underneath already.  If you needed random access to packets, then I'd understand, but I don't understand why it matters.

**Comment by supersonicnumbers** [comment] 2021-04-06 15:05
I was under the impression that using mmap would allow me to speed up the parsing by a few % (which would matter on my case, given the file sizes). Maybe I am wrong.

**Comment by mcr** [comment] 2021-04-06 15:54
You get a buffer from pcap which you read directly to parse.
The best speedup you could get would be that libpcap would become multi-thread, so that you could use multiple CPUs to parse.
Well, there is nothing to stop you from doing that now in your own application, but the problem is that you wind up having to copy the data.  I am working on an interface that assumes a different model underneath, and it would benefit from using mmap(2) [or multi-gigabyte capture buffers if live].
But if you think about it, being multi-thread is essentially saying you want non-sequential access to the data.
I'm going to close this issue.

**Closed by mcr** 2021-04-06 15:54 UTC
