### ISSUE TITLE
Don't stop the capture when the interface goes down on Linux

### ISSUE THREAD

**Issue by bamartin125** [the-tcpdump-group/libpcap#859] opened 2019-10-10 04:04 UTC
When an interface is brought down, it would be expected that the capture continue in the case that the interface is brought back up again.

This does not include cases where the interface is "gone for good" (eg. the interface was unplugged).

See issue [#402](https://github.com/the-tcpdump-group/libpcap/issues/402) for the Windows counterpart to this issue.

**Comment by bamartin125** [comment] 2019-10-10 04:05
Keying @guyharris into this issue directly.

**Comment by crass** [comment] 2019-11-04 20:05
I think unmerged #858 would be a good half-measure that would resolve a majority of users facing this issue.  I suspect most users run in to this when re-initializing the interface, not when a device disappears.

**Comment by guyharris** [comment] 2020-01-30 01:54
Should be fixed by a973128a85d7dd75c7ea6fdcf746fc143a987d03.

**Closed by guyharris** 2020-01-30 01:54 UTC

**Comment by guyharris** [comment] 2020-01-31 03:51
Note to anyone who wishes to argue that the interface being configured down *should* cause the capture to stop:

1. See this bug.

1. See [Wireshark bug 2653](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=2653), in which it's noted that this "[allows] debugging DHCP client problems", presumably because the interface may go down and up during the process.

Frankly, PF_PACKET sockets should allow you to bind to a non-up interface for the same reason.  \*BSD/macOS 1) have no problem with binding a BPF device to such an interface, 2) don't return an error for a read if the interface goes down, and 3) *do* return an error if the interface goes away.

Time permitting, I'll look at changing the PF_PACKET code to be more BSD-like (although though it should return an error if the interface goes down, but permit further reads, and return a *different* error if the interface goes away; that would let existing pcap APIs ignore "interface goes down" and more easily provide an error for "interface goes away", and let other code, possibly including future PCAP APIs, provide a *warning* for "interface went down" in case some program wants to note that).

**Comment by ag-TJNII** [comment] 2024-11-08 00:50
> *BSD/macOS 1) have no problem with binding a BPF device to such an interface, 2) don't return an error for a read if the interface goes down, and 3) do return an error if the interface goes away.

Sorry to resurrect an old issue but I have two follow-up questions to this:
1) Is this behehavior still what is expected at the end of 2024?
2) Is an error expected to be returned if the interface goes away on Linux?

Spirit of the question is I'm not seeing an error being thrown in my environment and I'm trying to figure out if it's expected, a libpcap issue, or an issue with the language binding around libpcap.  Thanks.

**Comment by guyharris** [comment] 2024-11-08 05:54
> Sorry to resurrect an old issue but I have two follow-up questions to this:

An interface going down won't cause an error; only the interface *disappearing* will. See [my previous comment](https://github.com/the-tcpdump-group/libpcap/issues/859#issuecomment-580048381).

**Comment by infrastation** [comment] 2024-11-08 08:09
If there seems to be a problem, please open a new issue and there describe the setup, the steps to reproduce, the expected behaviour and the observed behaviour.

**Comment by guyharris** [comment] 2024-11-08 08:21
> If there seems to be a problem, please open a new issue and there describe the setup, the steps to reproduce, the expected behaviour and the observed behaviour.

And if the problem is that you're *not* seeing an error if the interface goes down, please note that, as per [another earlier comment of mine](https://github.com/the-tcpdump-group/libpcap/issues/859#issuecomment-580569405), the lack of an error in that case is an intentional feature, not a bug, and is a behavior that people have requested; any change to that behavior will involve a new API to request it, so that the default behavior will remain the behavior that this bug report requested, and that [Wireshark bug 2653](https://gitlab.com/wireshark/wireshark/-/issues/2653) also indicated was desirable.

**Comment by ag-TJNII** [comment] 2024-11-08 13:25
> only the interface disappearing will [cause an error]

Okay, so an interface being removed should cause an error on Linux.  That answers my question.  I now need to peel some library onions to determine if what I'm seeing is a libpcap issue or an issue with the error handling in the language binding wrapper I'm using.  Thanks.

**Comment by guyharris** [comment] 2024-11-08 17:39
> Okay, so an interface being removed should cause an error on Linux. That answers my question. I now need to peel some library onions to determine if what I'm seeing is a libpcap issue or an issue with the error handling in the language binding wrapper I'm using. Thanks.

One thing I can definitely say is that the issue is not *this* issue, as *this* issue is a complaint that there *is* an error when an interface goes down, not that there *isn't* an error when an interface is *removed*, so, if it appears to be a libpcap issue, please file a *separate* issue.
