### ISSUE TITLE
Warnings with clang version 7.0.1 32 bits

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/libpcap#818] opened 2019-04-20 13:05 UTC
The warnings are:
```
./pcap-usb-linux.c:1213:29: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to '__time_t' (aka 'long') [-Wshorten-64-to-32]
        pkth.ts.tv_sec = info.hdr->ts_sec;
                       ~ ~~~~~~~~~~^~~~~~
./pcap-usb-linux.c:1328:26: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to '__time_t' (aka 'long') [-Wshorten-64-to-32]
                        pkth.ts.tv_sec = hdr->ts_sec;
                                       ~ ~~~~~^~~~~~
2 warnings generated.
./pcap-netfilter-linux.c:162:15: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
                if (ep - bp < NLMSG_SPACE(0)) {
                    ~~~~~~~ ^ ~~~~~~~~~~~~~~
./pcap-netfilter-linux.c:266:15: warning: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and 'int' [-Wsign-compare]
                if (msg_len > ep - bp)
                    ~~~~~~~ ^ ~~~~~~~
```

**Comment by infrastation** [comment] 2021-11-11 20:35
Do these compiler warnings still stand?

**Comment by guyharris** [comment] 2021-11-13 01:39
The pcap-usb-linux.c ones probably don't, as we explicitly cast the warning away in the tip of the main branch:

        pkth.ts.tv_sec = (time_t)info.hdr->ts_sec;

and

                        pkth.ts.tv_sec = (time_t)hdr->ts_sec;

The pcap-netfilter-linux ones probably don't, either, as we do a pile of casting to squelch the first one:

                /*
                 * NLMSG_SPACE(0) might be signed or might be unsigned,
                 * depending on whether the kernel defines NLMSG_ALIGNTO
                 * as 4, which older kernels do, or as 4U, which newer
                 * kernels do.
                 *
                 * ep - bp is of type ptrdiff_t, which is signed.
                 *
                 * To squelch warnings, we cast both to size_t, which
                 * is unsigned; ep >= bp, so the cast is safe.
                 */
                if ((size_t)(ep - bp) < (size_t)NLMSG_SPACE(0)) {
 
and the second one:

                /*
                 * If the message length would run past the end of the
                 * buffer, truncate it to the remaining space in the
                 * buffer.
                 *
                 * To squelch warnings, we cast ep - bp to uint32_t, which
                 * is unsigned and is the type of msg_len; ep >= bp, and
                 * len should fit in 32 bits (either it's set from an int
                 * or it's set from a recv() call with a buffer size that's
                 * an int, and we're assuming either ILP32 or LP64), so
                 * the cast is safe.
                 */
                if (msg_len > (uint32_t)(ep - bp))
                        msg_len = (uint32_t)(ep - bp);

**Comment by infrastation** [comment] 2021-11-22 00:19
If anybody would like to test the current code, the following 32-bit Linux distributions have Clang 7.0:
* Fedora 29
* OpenSuSE Leap 42, 15.1 and 15.2

**Comment by infrastation** [comment] 2021-11-22 21:21
Could not find the OpenSuSE install media, but installing Fedora 29 i686 worked. Default `build_matrix.sh` run, which includes Clang 7.0.1, passed without any compiler warnings. Closing.

**Closed by infrastation** 2021-11-22 21:21 UTC
Labels: compiling, needs-patch

**Comment by guyharris** [comment] 2021-11-22 21:30
> installing Fedora 29 i686 worked

Where did you find that?  I ended up cloning a Fedora 21 32-bit VM and doing a bunch of upgrades that got me to Fedora 29 (it took several steps, using various command-line upgrades for each step, plus one GUI upgrade, and one command-line step required removing a package due to a conflict).

**Comment by guyharris** [comment] 2021-11-22 21:39
> The warnings are:
> ```
> ./pcap-usb-linux.c:1213:29: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to '__time_t' (aka 'long') [-Wshorten-64-to-32]
>         pkth.ts.tv_sec = info.hdr->ts_sec;
>                        ~ ~~~~~~~~~~^~~~~~
> ./pcap-usb-linux.c:1328:26: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to '__time_t' (aka 'long') [-Wshorten-64-to-32]
>                         pkth.ts.tv_sec = hdr->ts_sec;
>                                        ~ ~~~~~^~~~~~
> 2 warnings generated.

What version of libpcap is this?  libpcap 1.9.0's pcap-usb-linux.c is only 1198 lines long.

> ```
> ./pcap-netfilter-linux.c:162:15: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
>                 if (ep - bp < NLMSG_SPACE(0)) {
>                     ~~~~~~~ ^ ~~~~~~~~~~~~~~
> ./pcap-netfilter-linux.c:266:15: warning: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and 'int' [-Wsign-compare]
>                 if (msg_len > ep - bp)
>                     ~~~~~~~ ^ ~~~~~~~
> ```

I was able to reproduce that with libpcap 1.9.0 on a Fedora 29 VM; as Denis noted, it doesn't appear with the current version.

**Comment by infrastation** [comment] 2021-11-22 21:46
Fedora keeps old releases in an archive, which is not available on all mirrors. Unlike Ubuntu, you cannot download from the release archive directly. There is a [status page](https://admin.fedoraproject.org/mirrormanager) for the mirrors, but it does not detect if a particular mirror with a particular release directory actually has anything in the directory, so it gives plenty of false positives and it becomes a wild goose chase.

There's another interface into the same system with a better hit rate. If you use [this link](https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-29&arch=i386), it will respond with a few URLs, once you are on the right mirror, go a couple levels up and back into "iso", and there it is.
