### ISSUE TITLE
Missing packets with filter in Windows 10

### ISSUE THREAD

**Issue by dcparga** [the-tcpdump-group/libpcap#455] opened 2015-09-08 12:06 UTC
Hi,

I've seen that some packages are missed running different tools based on libpcap. The purpose is to capture all the Request/Response send through SoapUI. For example, using dumpcap and windump, executing this command:

dumpcap -w resp_20150908.pcap -f "tcp port 80" 

will save the request, but the response is avoided. In the other hand, if the -f parameter is not set, the response is captured as well. And yes, the response goes through port 80. Capturing network data using Wireshark at the same time, the response is captured properly.

I've tested the dumpcap tool with two Windows 10 machines, and two Windows 7. The response appears in both win7, but not in any win10 machine.

Seeing the same problem with dumpcap and windump lead me to think that the problem came from libpcap.

**Comment by guyharris** [comment] 2015-09-08 16:43
> Capturing network data using Wireshark at the same time, the response is captured properly.

Are you capturing with Wireshark *on the same machine as the one on which you're capturing with dumpcap and WinDump*?  And are you capturing with the filter "tcp port 80" in both cases?

**Comment by dcparga** [comment] 2015-09-08 16:53
Yes, I am capturing in the same machine, and with tcp port 80 in both cases.

On Tue, 8 Sep 2015 at 18:43 Guy Harris <notifications@github.com> wrote:

> Capturing network data using Wireshark at the same time, the response is
> captured properly.
>
> Are you capturing with Wireshark *on the same machine as the one on which
> you're capturing with dumpcap and WinDump*? And are you capturing with
> the filter "tcp port 80" in both cases?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/the-tcpdump-group/libpcap/issues/455#issuecomment-138627535>
> .
>
-- 
Dani Caballero Parga

“In theory, there is no difference between theory and practice;
In practice, there is.”

**Comment by guyharris** [comment] 2015-09-08 17:31
So if you run dumpcap from the command line with that filter, it doesn't capture responses, but if you have Wireshark run dumpcap for you and read the file it's writing as it's writing it, it *does* capture responses?

Are you capturing with promiscuous mode enabled in Wireshark?

Are you capturing on the server, on the client, or on some third machine, passively sniffing the traffic?

Are you capturing on an Ethernet network, a Wi-Fi network, or some other type of network?

**Comment by dcparga** [comment] 2015-09-08 17:50
On Tue, 8 Sep 2015 at 19:31 Guy Harris <notifications@github.com> wrote:

> So if you run dumpcap from the command line with that filter, it doesn't
> capture responses, but if you have Wireshark run dumpcap for you and read
> the file it's writing as it's writing it, it *does* capture responses?
>
No exactly, what I did is: Run dumpcap with that filter, and at the same
time, wireshark sniffing the same interface, filtering with the same rule.
Then, after call the API in SoapUI, I see how dumpcap gets X packets, and
I'm able to see my response on wireshark. Then, I opened the file created
with dumpcap, and my response isn´t there.  I want to remark again that
doing exactly the same in a windows 10 machine, we get the same behaviour,
but not in two windows 7 machines.

> Are you capturing with promiscuous mode enabled in Wireshark?
>
Yes, and if I'm not wrong, the default mode for dumpcap is promiscous as
well.

> Are you capturing on the server, on the client, or on some third machine,
> passively sniffing the traffic?
>
I'm sniffing in the client (my local machine).

> Are you capturing on an Ethernet network, a Wi-Fi network, or some other
> type of network?
>
It's an Ethernet Network, but it's over a Open VPN connection.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/the-tcpdump-group/libpcap/issues/455#issuecomment-138642438>
> .
>
-- 
Dani Caballero Parga

“In theory, there is no difference between theory and practice;
In practice, there is.”

**Comment by guyharris** [comment] 2015-09-08 17:59
> No exactly, what I did is: Run dumpcap with that filter, and at the same
time, wireshark sniffing the same interface, filtering with the same rule.

So you have two instances of dumpcap running; Wireshark sniffs interfaces by running dumpcap to do the capturing and reads the file it writes.  One of the dumpcap instances is seeing your response and the other one isn't.

> Then, after call the API in SoapUI, I see how dumpcap gets X packets, and
I'm able to see my response on wireshark. Then, I opened the file created
with dumpcap, and my response isn´t there.

Did you stop dumpcap with control-C before opening its file?  Or did you open it while it's running?

**Comment by dcparga** [comment] 2015-09-08 18:03
>So you have two instances of dumpcap running; Wireshark sniffs interfaces by running dumpcap to do the capturing and reads the file it writes. One of the dumpcap instances is seeing your response and the other one isn't.

Yes, that's right. I want to clarify that the filter I applied to Wireshark is in the box on the top of the window, and I'm assuming that this is not the same filter dumpcap uses.

>Did you stop dumpcap with control-C before opening its file? Or did you open it while it's running?
Yes, first I stopped it with Control-C and then I opened the file with wireshark.

**Comment by guyharris** [comment] 2015-09-08 18:16
> I want to clarify that the filter I applied to Wireshark is in the box on the top of the window, and I'm assuming that this is not the same filter dumpcap uses.

It's not. It's the *display* filter; you can specify a *capture* filter when you set up the capture, and that's the filter Wireshark passes to dumpcap for use as its filter.

Do the responses have VLAN headers on any of the platforms on which you're capturing them?

**Comment by dcparga** [comment] 2015-09-08 18:34
>It's not. It's the display filter; you can specify a capture filter when you set up the capture, and that's the filter Wireshark passes to dumpcap for use as its filter.

Ok, my fault then. Thank you ;) 
But this still means that the response is received, and it has the correct port 80 (in destination), so it should appear in dumpcap. And I'll bet that applying that filter my package will disappear.

>Do the responses have VLAN headers on any of the platforms on which you're capturing them?

Nope. It's a standard HTTP/XML package containing my response.

**Comment by guyharris** [comment] 2015-09-08 18:43
> I'm sniffing in the client (my local machine).

So you're seeing the requests (packets from the client to the server), but not responses (packets from the server to the client)?

**Comment by guyharris** [comment] 2015-09-08 18:44
> > Do the responses have VLAN headers on any of the platforms on which you're capturing them?

> Nope. It's a standard HTTP/XML package containing my response.

So, in Wireshark, you see a 14-byte Ethernet header, followed by an IP (v4 or v6) header, followed by a TCP header, followed by HTTP and XML?

**Comment by guyharris** [comment] 2015-09-08 18:44
What version of WinPcap or Npcap are you using?

**Comment by dcparga** [comment] 2015-09-08 18:55
>So you're seeing the requests (packets from the client to the server), but not responses (packets from the server to the client)?

Right.

>So, in Wireshark, you see a 14-byte Ethernet header, followed by an IP (v4 or v6) header, followed by a TCP header, followed by HTTP and XML?

Yes, here you can see a screenshot of the response:
![image](https://cloud.githubusercontent.com/assets/11501633/9744374/c034b4f8-566b-11e5-874e-c0421d073ab4.png)

>What version of WinPcap or Npcap are you using?

WinPcap 4.1.3

**Comment by dcparga** [comment] 2015-09-08 19:10
Confirmed, with the same filter in Wireshark the response disappear, doing the same as dumpcap (logically).

**Comment by guyharris** [comment] 2015-09-09 00:12
> It's an Ethernet Network, but it's over a Open VPN connection.

So I assume by "Open VPN" you're referring to [OpenVPN](https://openvpn.net).

Are you capturing on your regular Ethernet interface ("Local Area Network Connection" or whatever Windows calls it), or does OpenVPN create a new (virtual) interface for the OpenVPN traffic, on which you're capturing?

(I've sent an e-mail to the winpcap-users mailing list about this; I have a suspicion what the problem is, but I don't know whether Windows 10 is actually doing what I suspect it might be doing here.)

**Comment by hsluoyz** [comment] 2015-09-09 02:48
You can try Npcap 1.00 (https://svn.nmap.org/nmap-exp/yang/NPcap-LWF/npcap-nmap-1.00.exe) to see what happens, as Npcap is a NDIS 6 update of WinPcap 4.1.3 and will always see one entire buffer for a single packet.

**Comment by dcparga** [comment] 2015-09-09 07:04
>So I assume by "Open VPN" you're referring to OpenVPN.

Yep.

>Are you capturing on your regular Ethernet interface ("Local Area Network Connection" or whatever Windows calls it), or does OpenVPN create a new (virtual) interface for the OpenVPN traffic, on which you're capturing?

It creates a virtual interface with TAP Windows and yes, this is the one I'm capturing.

**Comment by dcparga** [comment] 2015-09-09 07:36
Ok, I've installed Npcap and yes, now wireshark captures all the packages without problems!! Thank you Yang :+1: 

Guy, what is your suspicion? Just as a curiosity :)

**Comment by guyharris** [comment] 2015-09-09 10:02
> Guy, what is your suspicion? Just as a curiosity :)

That the routine in the WinPcap driver that's running the filter doesn't think it's been handed the complete packet - and, in this case, isn't being handed enough of the TCP header to get the port number - so the filter fails because it tries to refer to data past the end of the data it's been handed:

http://www.winpcap.org/pipermail/winpcap-users/2015-September/004962.html

I suspect that the WinPcap driver is making an incorrect assumption that might be valid with ordinary network drivers (where the entire packet is probably DMA'd into a single contiguous buffer) in a system using NDIS 5, but that the OpenVPN driver may be delivering the packet in a form that, when it passes through the NDIS 6 to NDIS 5 shim (I'm assuming the NDIS 6 version of the OpenVPN driver is running, and WinPcap only has an NDIS 5 driver), violates that assumption.

Npcap, on Windows 7 and later, has an NDIS 6 driver, and probably isn't making that assumption.

**Comment by guyharris** [comment] 2015-09-09 10:28
> I suspect that the WinPcap driver is making an incorrect assumption

Or perhaps not, but the Windows 10 NDIS 6 to NDIS 5 shim may still not be handling the packets from the OpenVPN driver in a way that lets the WinPcap driver work:

http://www.winpcap.org/pipermail/winpcap-users/2015-September/004964.html

**Comment by dcparga** [comment] 2015-09-09 16:49
Cool, thank you! Let's see how evolve this issue.

**Comment by sadiksikder** [comment] 2017-08-22 08:50
can i see your source code?

**Comment by infrastation** [comment] 2021-11-11 21:36
Did this discussion result in a problem statement or a note to add to a man page or the FAQ?

**Comment by guyharris** [comment] 2021-11-12 23:46
At this point:

- with WinPcap, the problem *might* be that the filtering code isn't looking at the entire packet because it's contained in multiple buffers (probably an alien concept to Linux kernel network developers, but familiar to kernel network developers from BSD-flavored OSes, who may know the term "mbuf chain");
- the problem appears to be fixed in Npcap;
- the problem isn't in *our* code in any case.

WinPcap isn't supported, so it's unlikely ever to be fixed.

It works with Npcap, and Wireshark now bundles Npcap rather than WinPcap, so this problem probably won't show up very often in the future.  My inclination is just to close it as "fixed in Npcap".

**Comment by infrastation** [comment] 2021-11-13 00:30
So be it.

**Closed by infrastation** 2021-11-13 00:30 UTC
Labels: runtime
