### ISSUE TITLE
libpcap doesn't find VLAN packets

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#154] opened 2013-04-15 23:21 UTC
Converted from [SourceForge issue 3391397](http://sourceforge.net/support/tracker.php?aid=3391397), submitted by blu3viper

tcpdump 4.2.0rc1
libpcap 1.2.0rc1
Linux kernel 3.0.1
Linux headers 2.6.38

> > tcpdump -ennlxx -i tap0 vlan
> > results in zero packets ever matching
> > 
> > tcpdump -ennlxx -i tap0 ether src 00:e0:81:27:68:08
> > shows all the applicable packets, with the VLAN tag decoded

e.g.
06:04:38.101881 00:e0:81:27:68:08 > 2e:d2:07:2c:5f:22, ethertype 802.1Q (0x8100), length 96: vlan 200, p 0, ethertype IPv4, 192.168.26.1.137 > 192.168.26.240.137: NBT UDP PACKET(137): QUERY; REQUEST; UNICAST
        0x0000:  2ed2 072c 5f22 00e0 8127 6808 8100 00c8
        0x0010:  0800 4500 004e d493 4000 4011 afc9 c0a8
        ...

referencing http://netoptimizer.blogspot.com/2010/09/tcpdump-vs-vlan-tags.html, the libpcap configure indicated "yes" for tpacket_aux.  additionally i was under the impression that the needed changes were applied for this release.

**Comment by infrastation** [comment] 2021-10-05 16:04
The original bug report was made on 2011-08-14, it concerns a libpcap version released in 2011 and a tcpdump version released in 2011. The bug does not reproduce on the current master branches (Linux kernel 5.11.0), which is expected given how many VLAN and Linux improvements have been made in the 10 years since then. Closing.

**Closed by infrastation** 2021-10-05 16:04 UTC
Labels: runtime, bug
