### ISSUE TITLE
Packets are not always captured

### ISSUE THREAD

**Issue by Sworddragon** [the-tcpdump-group/libpcap#383] opened 2014-10-02 08:27 UTC
I'm using Linux 3.16.3 (x86_64) with libpcap 1.6.2 and I have found a case where packets are not captured. Here is the testcase:

```
#include <pcap.h>
#include <time.h>

int main()
{
    char error[PCAP_ERRBUF_SIZE];
    pcap_t *capture;
    struct pcap_pkthdr header;
    struct pcap_stat statistic;

    printf("%s\n", pcap_lib_version());
    if((capture = pcap_create("eth0", error)) == NULL)
    {
        printf("%s\n", error);
        return 1;
    }
    pcap_set_timeout(capture, 15000);
    pcap_activate(capture);
    for(;;)
        if(pcap_next(capture, &header) == NULL)
        {
            pcap_stats(capture, &statistic);
            printf("Timeout (%i packet(s) captured, %i packet(s) dropped)\n", statistic.ps_recv, statistic.ps_drop + statistic.ps_ifdrop);
        }
        else
            printf("Packet captured (delayed for %i second(s))\n", (int)time(NULL) - (int)header.ts.tv_sec);
    pcap_close(capture);
    return 0;
}
```

On executing this I'm seeing:
- Downloading something or permanently pinging a server (1 second interval) works fine.
- Playing a game (in this case Guild Wars 2) causes the timeout to trigger (checking Guild Wars 2 with Wireshark confirms that this game is continuously creating ~20 network packages per second on idle).
- Running Guild Wars 2 and permanently pinging a server (1 second interval) causes a timeout.

**Comment by infrastation** [comment] 2015-03-25 13:54
Can you check if the problem is still present with libpcap 1.7.2?

**Comment by guyharris** [comment] 2015-03-26 00:32
...and with a 3.19.x kernel, as [it includes](http://www.spinics.net/lists/netdev/msg309630.html) [the patch I referred to earlier](http://www.spinics.net/lists/netdev/msg309291.html)

**Comment by Sworddragon** [comment] 2015-03-29 10:34
With the Linux kernel 3.19.2 and libpcap 1.6.2 the issue does still exist. After compiling libpcap 1.7.2 and installing it with "make install" my system does still prefer its installed version (1.6.2) after recompiling the testcase. I will test this again if libpcap 1.7.2 or higher lands in Ubuntu. Also I have updated the testcase in the startpost to show which version of libpcap is in use.

**Comment by Sworddragon** [comment] 2015-05-27 11:29
With the linux kernel 3.19.6 and libpcap 1.7.3 I'm still able to reproduce this issue.

**Comment by guyharris** [comment] 2015-05-27 19:39
So are packets getting *dropped*, or is this just a case of packet delivery being *delayed*, i.e. you get no packets in one interval but get them in a later interval?

I.e., remove the "break;" after printing "Timeout", as a timeout isn't an *error*, it's just an indication that, for whatever reason, the OS's packet capture mechanism didn't deliver packets in that interval.

**Comment by Sworddragon** [comment] 2015-06-01 16:11
Removing the break results that I'm still seeing packets being captured after a timeout (but I can't tell if the old packets got dropped or just delayed). But I'm wondering why only pinging a server doesn't cause a timeout while pinging a server + creating other network traffic seems to do. But maybe libpcap can try to force the kernel to flush out all packets on the end of an interval?

**Comment by guyharris** [comment] 2015-06-02 02:13
> (but I can't tell if the old packets got dropped or just delayed)

Try calling `pcap_stats()`and see what the `ps_drop` count is; that should report packets that the capture mechanism dropped because the capture buffer in the kernel filled up because it wasn't being drained fast enough.

**Comment by guyharris** [comment] 2015-06-02 02:18
When you say both

* Playing a game (in this case Guild Wars 2) causes the timeout to trigger (checking Guild Wars 2 with Wireshark confirms that this game is continuously creating ~20 network packages per second on idle).

and

* Running Guild Wars 2 and permanently pinging a server (1 second interval) causes a timeout;

does that mean "Running Guild Wars 2 causes timeouts, regardless of whether there's pinging or not"?

What happens if you use 1000 (the standard tcpdump timeout) or 500 (the standard Wireshark timeout) as the timeout, rather than 15000?  Are tcpdump and Wireshark both using the same version of libpcap as your program is using?  (`tcpdump -h` or `wireshark -v`/"About Wireshark" in the menu.)

**Comment by Sworddragon** [comment] 2015-06-02 18:23
I have updated the testcase to include also statistics. But on the tests now I have noticed that only pinging a server does cause a timeout too so in the past I was maybe just lucky to not get the timeout there. And yes, Guild Wars 2 causes a timeout on my testcase no matter if I'm pinging a server or not. Also "wireshark -v" confirms that it is using the same version of libpcap as my testcase.

To the results:

- No matter in which case I'm getting the timeout there are always 0 packets dropped (so they seem to get delayed then).
- Using a timeout of 1000 causes the timeout to appear too but much later.

**Comment by guyharris** [comment] 2015-06-02 19:53
What's interesting is less whether you get timeouts than how long the packets get delayed.  In your program, try getting the current time and showing the delta between the time in the `struct pcap_pkthdr` and the current time.

**Comment by Sworddragon** [comment] 2015-06-03 18:43
I have updated the testcase to also show the delay. On testing this I'm seeing that the delay in an interval for the packets captured goes from 14/15 seconds down to 0/1 second. If a timeout appears the next packets captured will have the same pattern. I have not seen a package that had a delay longer than 15 seconds.

**Comment by guyharris** [comment] 2015-06-03 18:46
> On testing this I'm seeing that the delay in an interval for the packets captured goes from 14/15 seconds down to 0/1 second.

"Goes down" as a result of what?  Changing the timeout from 15000 to 1000?

> I have not seen a package that had a delay longer than 15 seconds.

Not surprising, given that you originally set the timeout to 15000 milliseconds, i.e. 15 seconds.

**Comment by Sworddragon** [comment] 2015-06-03 18:57
>"Goes down" as a result of what? Changing the timeout from 15000 to 1000?

No, I was meaning that from the multiple packets I'm getting per interval they are counting down the delay in groups from 14/15 seconds to 0/1 second.

**Comment by guyharris** [comment] 2015-06-03 19:25
I.e., you see, in order, a delay of 14/15, 13/14, 12/13, ... 2/3, 1/2, 0/1, and then back to 14/15, followed by 13/14, ..., and so on, over and over again?

**Comment by Sworddragon** [comment] 2015-06-03 19:35
Yes, here is how it looks on 3 intervals (the second one triggered a timeout at the beginning) on pinging a server:

>root@ubuntu:/home/sworddragon/tmp# ./test
libpcap version 1.7.3
Packet captured (delayed for 14 second(s))
Packet captured (delayed for 14 second(s))
Packet captured (delayed for 13 second(s))
Packet captured (delayed for 13 second(s))
Packet captured (delayed for 12 second(s))
Packet captured (delayed for 12 second(s))
Packet captured (delayed for 11 second(s))
Packet captured (delayed for 11 second(s))
Packet captured (delayed for 10 second(s))
Packet captured (delayed for 10 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 8 second(s))
Packet captured (delayed for 8 second(s))
Packet captured (delayed for 8 second(s))
Packet captured (delayed for 7 second(s))
Packet captured (delayed for 7 second(s))
Packet captured (delayed for 6 second(s))
Packet captured (delayed for 6 second(s))
Packet captured (delayed for 5 second(s))
Packet captured (delayed for 5 second(s))
Packet captured (delayed for 4 second(s))
Packet captured (delayed for 4 second(s))
Packet captured (delayed for 3 second(s))
Packet captured (delayed for 3 second(s))
Packet captured (delayed for 2 second(s))
Packet captured (delayed for 2 second(s))
Packet captured (delayed for 1 second(s))
Packet captured (delayed for 1 second(s))
Packet captured (delayed for 0 second(s))
Packet captured (delayed for 0 second(s))
Packet captured (delayed for 0 second(s))
Packet captured (delayed for 0 second(s))
Timeout (68 packet(s) captured, 0 packet(s) dropped)
Packet captured (delayed for 14 second(s))
Packet captured (delayed for 14 second(s))
Packet captured (delayed for 13 second(s))
Packet captured (delayed for 13 second(s))
Packet captured (delayed for 12 second(s))
Packet captured (delayed for 12 second(s))
Packet captured (delayed for 11 second(s))
Packet captured (delayed for 11 second(s))
Packet captured (delayed for 10 second(s))
Packet captured (delayed for 10 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 8 second(s))
Packet captured (delayed for 8 second(s))
Packet captured (delayed for 7 second(s))
Packet captured (delayed for 7 second(s))
Packet captured (delayed for 6 second(s))
Packet captured (delayed for 6 second(s))
Packet captured (delayed for 5 second(s))
Packet captured (delayed for 5 second(s))
Packet captured (delayed for 4 second(s))
Packet captured (delayed for 4 second(s))
Packet captured (delayed for 3 second(s))
Packet captured (delayed for 3 second(s))
Packet captured (delayed for 2 second(s))
Packet captured (delayed for 2 second(s))
Packet captured (delayed for 2 second(s))
Packet captured (delayed for 1 second(s))
Packet captured (delayed for 1 second(s))
Packet captured (delayed for 0 second(s))
Packet captured (delayed for 0 second(s))
Packet captured (delayed for 14 second(s))
Packet captured (delayed for 14 second(s))
Packet captured (delayed for 13 second(s))
Packet captured (delayed for 13 second(s))
Packet captured (delayed for 12 second(s))
Packet captured (delayed for 12 second(s))
Packet captured (delayed for 11 second(s))
Packet captured (delayed for 11 second(s))
Packet captured (delayed for 10 second(s))
Packet captured (delayed for 10 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 9 second(s))
Packet captured (delayed for 8 second(s))
Packet captured (delayed for 8 second(s))
Packet captured (delayed for 7 second(s))
Packet captured (delayed for 7 second(s))
Packet captured (delayed for 6 second(s))
Packet captured (delayed for 6 second(s))
Packet captured (delayed for 5 second(s))
Packet captured (delayed for 5 second(s))
Packet captured (delayed for 4 second(s))
Packet captured (delayed for 4 second(s))
Packet captured (delayed for 3 second(s))
Packet captured (delayed for 3 second(s))
Packet captured (delayed for 2 second(s))
Packet captured (delayed for 2 second(s))
Packet captured (delayed for 1 second(s))
Packet captured (delayed for 1 second(s))
Packet captured (delayed for 0 second(s))
Packet captured (delayed for 0 second(s))
^C

**Comment by guyharris** [comment] 2015-06-03 19:48
OK, try doing

    for(;;) {
        int npackets;

        printf("Waiting for a batch of packets\n");
        npackets = pcap_dispatch(capture, -1, callback, NULL);
        if (npackets == 0) {
            pcap_stats(capture, &statistic);
            printf("Timeout (%i packet(s) captured, %i packet(s) dropped)\n", statistic.ps_recv, statistic.ps_drop + statistic.ps_ifdrop);
        }
    }

and have `callback()` be

    static void
    callback(u_char *dummy, const struct pcap_pkthdr *header, const u_char *bytes)
    {
        printf("Packet captured (delayed for %i second(s))\n", (int)time(NULL) - (int)header->ts.tv_sec);
    }

and see what it prints.

**Comment by Sworddragon** [comment] 2015-06-03 20:10
Could you reproduce with the current testcase the state of my last post on a recent 64 bit Linux system with a kernel version 3.19.x (as I'm very busy with other things too)?

**Comment by guyharris** [comment] 2015-06-03 22:40
OK, time for Yet Another Virtual Machine; that flash memory on my MBP wasn't doing anything useful anyway.... :-)

If, on that virtual machine (Ubuntu 15.04) I build the test program, with the changes I mentioned, plus a change to add a capture filter of "icmp" (for reasons I'll explain in a bit) and with a timeout of 15000 - i.e., 15 seconds - with the current trunk version of libpcap, and run it on the kernel that comes with it (Linux 3.19.0-18-generic), and, in another window, just run a ping, I get:

    libpcap version 1.8.0-PRE-GIT_2015_06_03
    Waiting for a batch of packets
    Timeout (0 packet(s) captured, 0 packet(s) dropped)
    Waiting for a batch of packets
    Timeout (22 packet(s) captured, 0 packet(s) dropped)
    Waiting for a batch of packets
    Packet captured (delayed for 11 second(s))
    Packet captured (delayed for 11 second(s))
    Packet captured (delayed for 10 second(s))
    Packet captured (delayed for 10 second(s))
    Packet captured (delayed for 9 second(s))
    Packet captured (delayed for 9 second(s))
    Packet captured (delayed for 8 second(s))
    Packet captured (delayed for 8 second(s))
    Packet captured (delayed for 7 second(s))
    Packet captured (delayed for 7 second(s))
    Packet captured (delayed for 6 second(s))
    Packet captured (delayed for 6 second(s))
    Packet captured (delayed for 5 second(s))
    Packet captured (delayed for 5 second(s))
    Packet captured (delayed for 4 second(s))
    Packet captured (delayed for 4 second(s))
    Packet captured (delayed for 3 second(s))
    Packet captured (delayed for 3 second(s))
    Packet captured (delayed for 2 second(s))
    Packet captured (delayed for 2 second(s))
    Packet captured (delayed for 1 second(s))
    Packet captured (delayed for 1 second(s))
    Packet captured (delayed for 0 second(s))
    Waiting for a batch of packets
    Timeout (52 packet(s) captured, 0 packet(s) dropped)
    Waiting for a batch of packets
    Packet captured (delayed for 15 second(s))
    Packet captured (delayed for 14 second(s))
    Packet captured (delayed for 14 second(s))
    Packet captured (delayed for 13 second(s))
    Packet captured (delayed for 13 second(s))
    Packet captured (delayed for 12 second(s))
    Packet captured (delayed for 12 second(s))
    Packet captured (delayed for 11 second(s))
    Packet captured (delayed for 11 second(s))
    Packet captured (delayed for 10 second(s))
    Packet captured (delayed for 10 second(s))
    Packet captured (delayed for 9 second(s))
    Packet captured (delayed for 9 second(s))
    Packet captured (delayed for 8 second(s))
    Packet captured (delayed for 8 second(s))
    Packet captured (delayed for 7 second(s))
    Packet captured (delayed for 7 second(s))
    Packet captured (delayed for 6 second(s))
    Packet captured (delayed for 6 second(s))
    Packet captured (delayed for 5 second(s))
    Packet captured (delayed for 5 second(s))
    Packet captured (delayed for 4 second(s))
    Packet captured (delayed for 4 second(s))
    Packet captured (delayed for 3 second(s))
    Packet captured (delayed for 3 second(s))
    Packet captured (delayed for 2 second(s))
    Packet captured (delayed for 2 second(s))
    Packet captured (delayed for 1 second(s))
    Packet captured (delayed for 1 second(s))
    Packet captured (delayed for 0 second(s))
    Waiting for a batch of packets

which is, other than the timeouts, *exactly* what I expected.

If I do the same thing, except for capturing on "en0" rather than "eth0", on my MBP (running Mountain Lion), and linked with the libpcap that comes with the system (a newer libpcap won't make a difference here - both versions just use the BPF in the kernel), I get:

    libpcap version 1.1.1
    Waiting for a batch of packets
    Packet captured (delayed for 12 second(s))
    Packet captured (delayed for 12 second(s))
    Packet captured (delayed for 11 second(s))
    Packet captured (delayed for 11 second(s))
    Packet captured (delayed for 10 second(s))
    Packet captured (delayed for 10 second(s))
    Packet captured (delayed for 9 second(s))
    Packet captured (delayed for 9 second(s))
    Packet captured (delayed for 8 second(s))
    Packet captured (delayed for 8 second(s))
    Packet captured (delayed for 7 second(s))
    Packet captured (delayed for 7 second(s))
    Packet captured (delayed for 6 second(s))
    Packet captured (delayed for 6 second(s))
    Packet captured (delayed for 5 second(s))
    Packet captured (delayed for 5 second(s))
    Packet captured (delayed for 4 second(s))
    Packet captured (delayed for 4 second(s))
    Packet captured (delayed for 3 second(s))
    Packet captured (delayed for 3 second(s))
    Packet captured (delayed for 2 second(s))
    Packet captured (delayed for 2 second(s))
    Packet captured (delayed for 1 second(s))
    Packet captured (delayed for 1 second(s))
    Packet captured (delayed for 0 second(s))
    Packet captured (delayed for 0 second(s))
    Waiting for a batch of packets
    Packet captured (delayed for 14 second(s))
    Packet captured (delayed for 14 second(s))
    Packet captured (delayed for 13 second(s))
    Packet captured (delayed for 13 second(s))
    Packet captured (delayed for 12 second(s))
    Packet captured (delayed for 12 second(s))
    Packet captured (delayed for 11 second(s))
    Packet captured (delayed for 11 second(s))
    Packet captured (delayed for 10 second(s))
    Packet captured (delayed for 10 second(s))
    Packet captured (delayed for 9 second(s))
    Packet captured (delayed for 9 second(s))
    Packet captured (delayed for 8 second(s))
    Packet captured (delayed for 8 second(s))
    Packet captured (delayed for 7 second(s))
    Packet captured (delayed for 7 second(s))
    Packet captured (delayed for 6 second(s))
    Packet captured (delayed for 6 second(s))
    Packet captured (delayed for 5 second(s))
    Packet captured (delayed for 5 second(s))
    Packet captured (delayed for 4 second(s))
    Packet captured (delayed for 4 second(s))
    Packet captured (delayed for 3 second(s))
    Packet captured (delayed for 3 second(s))
    Packet captured (delayed for 2 second(s))
    Packet captured (delayed for 2 second(s))
    Packet captured (delayed for 1 second(s))
    Packet captured (delayed for 1 second(s))
    Packet captured (delayed for 0 second(s))
    Packet captured (delayed for 0 second(s))
    Waiting for a batch of packets

which is exactly the result I expected, and which is pretty much the same as the results on Linux, except for the lack of timeouts.

So the application gets a batch of packets every 15 seconds, that being the timeout.  That's because BPF - and mechanisms such as TPACKET_V3 PF_PACKET sockets, which do buffering in a very similar fashion - don't, by default, immediately deliver packets as they arrive.  Instead, they store them in a buffer and, if the buffer fills up or the timeout (if one is specified, which it pretty much always should be) expires, deliver the entire bufferful of packets to userland.  This is done to amortize the cost of kernel <-> userland transitions over a large number of packets.

The only odd thing is the timeouts on Linux.  It appears that either 1) TPACKET_V3 is delivering extra wakeups or 2) libpcap is somehow, on a wakeup, finding both an empty buffer and a buffer full of packets.  I'll look at that.

**Comment by guyharris** [comment] 2015-06-04 07:28
The answer is 3) `poll()` was, to work around some TPACKET_V3 issues, being handed a timeout, so a wakeup came from a `poll()` timeout rather than from TPACKET_V3's timeout, and those wakeups turned into timeouts reported by libpcap.  The timeout isn't needed on libpcap 3.19 and later; not doing it in 3.19 and later appears to make the extra timeouts go away.

So, unless you can see the extra timeouts, this is fixed.  I'm not a gamer, so I can't do the "Playing a game (in this case Guild Wars 2) causes the timeout to trigger" test; you'll have to do that one yourself.

**Comment by Sworddragon** [comment] 2015-06-04 15:42
Thanks for taking the time to test this and to also fix this (I will test this later on myself too) :)
But there is one thing I'm not sure I'm translating it correctly:

>which is, other than the timeouts, exactly what I expected.

You wanted to say that the result is what you expected except for the timeouts?

**Comment by guyharris** [comment] 2015-06-04 16:20
> You wanted to say that the result is what you expected except for the timeouts?

Yes.  What I expected is output similar to what I got on OS X (and would also have gotten on *BSD).

**Comment by Sworddragon** [comment] 2015-06-04 19:16
I have thought about this a little: Wouldn't handing the timeout to poll() for kernel versions <= 3.18.x as workaround still cause applications there to get "false" timeouts? But maybe we have to live with this as these versions will get over time more and more outdated.

**Comment by guyharris** [comment] 2015-06-04 19:52
> Wouldn't handing the timeout to poll() for kernel versions <= 3.18.x as workaround still cause applications there to get "false" timeouts?

Yes, but false timeouts are better than lost packets.

> But maybe we have to live with this as these versions will get over time more and more outdated.

Yes.

**Comment by infrastation** [comment] 2021-10-05 16:11
This libpcap API usage consultation was resolved in 2015.

**Closed by infrastation** 2021-10-05 16:11 UTC
Labels: runtime, generic support
