### ISSUE TITLE
A centos patch on libpcap version 1.5.3 causes the creation of invalid pcap files with packet length < capture length when capturing on the "any" interface

### ISSUE THREAD

**Issue by yousong** [the-tcpdump-group/libpcap#1071] opened 2021-11-25 10:13 UTC
The dump was captured with tcpdump 4.9.2 and libpcap 1.5.3, [likely with distro patch applied](https://git.centos.org/rpms/libpcap/blob/c7/f/SOURCES/0001-bpf-increase-snaplen-if-doing-cooked-mode-userspace-.patch).  The capture command is `tcpdump -i any -nn -w a.pcap`.  `-i any` matters as otherwise the issue did not appear.

```
tcpdump version 4.9.2
libpcap version 1.5.3
OpenSSL 1.0.2k-fips  26 Jan 2017
```

When read on another machine with tcpdump 4.99, the command will fail with things like `[Invalid header: len(100) < caplen(116)]` for each packet in the packet.  The error message says snaplen of a packet is actually 16 bytes bigger than the actual length.  It's always 16 bytes gap for all packets when this issue happened

My preliminary analysis leads me to think that the 16 bytes was `struct sll_header` whose size is exactly 16 bytes and the hexdump seems to matches the struct fields.

The issue did not happen with newer version of libpcap.  That is the same tcpdump executable binary but newer versions of libc, libpcap, etc.

```
a version 4.9.2
libpcap version 1.10.1 (with TPACKET_V3)
OpenSSL 1.0.2k-fips  26 Jan 2017
```

A hexdump of a.pcap

```
00000000  d4 c3 b2 a1 02 00 04 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 04 00 71 00 00 00  cb 5e 9f 61 ae 80 04 00  |....q....^.a....|
00000020  c9 03 00 00 b9 03 00 00  00 00 00 01 00 06 ee ff  |................|
          ^^          ^^                          ^^ ^^ ^^
00000030  ff ff ff ff 00 00 08 00  45 14 03 a9 a7 2e 40 00  |........E.....@.|
          ^^ ^^ ^^ ^^ ^^ ^^
```

`06` should be hardware address length, and the following bytes also match

The issue was originally reported at: https://github.com/the-tcpdump-group/tcpdump/commit/9e6ba479d8cee861a396cae59d7cf91bd3a5a563

And `grep 'reading from file'` output

```
a: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
```

**Comment by yousong** [comment] 2021-11-30 03:59
> So I suspect cooked-capture (`LINKTYPE_LINUX_SLL`) files written by this badly-broken version of libpcap will have 16 bytes of junk at the end of every packet, as the dump code will trust the too-large-by-16 captured length and will write out whatever crap is in the 16 bytes after the end of the packet (assuming that doesn't run past the end of the address space, in which case it'll just crash).

True.  Thanks for the in-depth analysis.  I also noticed that extra 16 bytes too and planned to investigate on that at a later time.

> If we were to implement this workaround, we'd need a sample file with which to test it.

In case it can still be useful, I attached a small pcap file containing several icmp echo request/reply packets.

[icmp.pcap.tar.gz](https://github.com/the-tcpdump-group/libpcap/files/7622764/icmp.pcap.tar.gz)

hexdump of the first few bytes of the pcap file

```
00000000  d4 c3 b2 a1 02 00 04 00  00 00 00 00 00 00 00 00  |................|
00000010  00 00 04 00 71 00 00 00  be 9e a5 61 f1 81 0d 00  |....q......a....|
00000020  74 00 00 00 64 00 00 00  00 04 00 01 00 06 00 16  |t...d...........|
          ^^          ^^

```

"tcpdump -X" with the buggy libpcap

```
reading from file icmp.pcap, link-type LINUX_SLL (Linux cooked)
11:47:10.885233 IP 172.20.16.207 > 114.114.114.114: ICMP echo request, id 16274, seq 1, length 64
        0x0000:  4500 0054 64dd 4000 4001 3404 ac14 10cf  E..Td.@.@.4.....
        0x0010:  7272 7272 0800 aa17 3f92 0001 be9e a561  rrrr....?......a
        0x0020:  0000 0000 de81 0d00 0000 0000 1011 1213  ................
        0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
        0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
        0x0050:  3435 3637 0000 0000 be9e a561 b060 4a35  4567.......a.`J5
                           ^^^^ ^^^^ ^^^^ ^^^^ ^^^^ ^^^^     
        0x0060:  5400 0000                                T...
                 ^^^^ ^^^^
```

**Comment by yousong** [comment] 2021-11-30 04:06
> I very sincerely hope that this isn't also an issue in RHEL 7, or whatever the RHEL version is that corresponds to CentOS 7.

My understanding is that CentOS literally uses source code from RHEL and does very little modification on its own.  Very likely the issue is still there for RHEL 7 and many derivatives besides CentOS 7.

My past experience with coreutils indicates to me that the issue has to be fixed in RHEL first and it will not be fast and straightforward like here with the-tcpdump-group.

This issue report here should suffice serving archive purposes, should other users also encounter it in the future.

**Comment by infrastation** [comment] 2021-11-30 13:47
This bug belongs to the CentOS package, please file it with CentOS and let the package maintainers see this problem. It is their responsibility to come up with a solution, in whatever way makes the most sense to them.

**Comment by yousong** [comment] 2021-12-01 02:20
The issue is now also in bugs.centos.org: https://bugs.centos.org/view.php?id=18365

**Comment by msekletar** [comment] 2021-12-01 19:37
Offending line is in the downstream patch,
https://git.centos.org/rpms/libpcap/blob/c7/f/SOURCES/0001-bpf-make-sure-sll-header-size-if-accounted-for.patch#_31

Back then I was debugging the issue were with TPACKET_V2+LINUX_SLL (Linux cooked) the first packet was incorrectly filtered out. (#405) Downstream patch https://git.centos.org/rpms/libpcap/blob/c7/f/SOURCES/0001-bpf-make-sure-sll-header-size-if-accounted-for.patch#_31 actually fixed the issue (verified by Red Hat QE, but I was not sure about the approach so I've just filed the issue #405 instead of sending PR). Later I backported couple more upstream patches which interfered with this previous change. So I introduced another patch to fix the problem (clash of upstream changes with my downstream patch) but I've made the mistake.

Anyway, all this is now mostly moot because after some kernel fixes we (actually the new libpcap maintainer at RH) were able to re-enable TPACKET_V3 even in RHEL-7. Bug that I was fixing doesn't even reproduce with TPACKET_V3.

At this point I propose to fix the libpcap downstream (I will work with current maintainer to get this resolved, updates via Bugzilla) and don't introduce any compat code in recent version to be able to read these broken savefiles.

**Comment by infrastation** [comment] 2021-12-02 13:48
Thank you for explaining the origins of this issue. As far as it makes sense to me, if the problem was downstream, it would be best to apply the solution downstream too.

**Comment by infrastation** [comment] 2021-12-09 19:33
Closing as advised earlier. CentOS package maintainers are welcome to add a comment for posterity later if they wish.

**Closed by infrastation** 2021-12-09 19:33 UTC

**Comment by mruprich** [comment] 2022-05-11 12:40
Hi all,
I've fixed this in RHEL7 but I am not entirely sure when this will get into CentOS.
Regards,
Michal

**Comment by infrastation** [comment] 2022-05-11 13:48
That's nice to know, thank you!
