### ISSUE TITLE
pcap_dispatch() does not respect its cnt argument

### ISSUE THREAD

**Issue by Guinpen** [the-tcpdump-group/libpcap#493] opened 2016-05-08 11:15 UTC
The pcap_dispatch() function does not respect its second argument (cnt). From the manual:

> pcap_dispatch() processes packets from a live capture [...] until cnt packets are processed [...] Thus, when doing a live capture, **cnt is the maximum number of packets to process** before returning [...]

However, the following program demonstrates that pcap_dispatch() often continues beyond that maximum:

``` c
#include <stdio.h>
#include <unistd.h>
#include <pcap/pcap.h>

void pcap_callback(u_char* ptr, const struct pcap_pkthdr* header, const u_char* packet) {}

int main() {
    char error_buf[PCAP_ERRBUF_SIZE];
    pcap_t* pcap = pcap_create("mon0", error_buf);
    if (!pcap) {
        puts(error_buf);
        return 1;
    }
    pcap_set_snaplen(pcap, 256);
    pcap_set_promisc(pcap, 1);
    int rc = pcap_can_set_rfmon(pcap);
    if (rc == PCAP_ERROR) {
        puts(pcap_geterr(pcap));
        return 1;
    }
    else if (rc != 1) {
        return 1;
    }
    pcap_set_rfmon(pcap, 1);
    pcap_set_timeout(pcap, 100);
    pcap_set_buffer_size(pcap, 64 * 1024 * 1024);
    if (pcap_set_tstamp_type(pcap, PCAP_TSTAMP_HOST))
        return 1;

    rc = pcap_activate(pcap);
    if (rc == PCAP_ERROR || rc == PCAP_WARNING || rc == PCAP_WARNING_PROMISC_NOTSUP
        || rc == PCAP_ERROR_NO_SUCH_DEVICE || rc == PCAP_ERROR_PERM_DENIED) {
        puts(pcap_geterr(pcap));
        return 1;
    }
    else if (rc) {
        return 1;
    }
    if (pcap_set_datalink(pcap, DLT_IEEE802_11_RADIO)) {
        puts(pcap_geterr(pcap));
        return 1;
    }

    for (int i = 0; i < 10; ++i) {
        int rc = pcap_dispatch(pcap, 256, &pcap_callback, 0);
        if (rc == -1) {
            puts(pcap_geterr(pcap));
            return 1;
        }
        printf("rc = %d\n", rc);
        struct pcap_stat stats;
        if (pcap_stats(pcap, &stats)) {
            puts(pcap_geterr(pcap));
            return 1;
        }
        printf("stats = %d %d %d\n", stats.ps_recv, stats.ps_drop, stats.ps_ifdrop);
        sleep(5);
    }

    pcap_close(pcap);
    return 0;
}
```

Compile with: `gcc -std=gnu11 -Wall -march=x86-64 -mtune=generic -O0 -ggdb3 test.c -lpcap -o test`

Sample run:
```
rc = 6
stats = 6 0 0
rc = 241
stats = 247 0 0
rc = 259
stats = 516 0 0
rc = 260
stats = 766 0 0
rc = 259
stats = 1029 0 0
rc = 256
stats = 1291 0 0
rc = 257
stats = 1559 0 0
rc = 258
stats = 1811 0 0
rc = 258
stats = 2064 0 0
rc = 257
stats = 2316 0 0
```

Environment: Arch Linux, `Linux devzbox 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux`, libpcap 1.7.4

Please let me know if I can provide more info. Thanks!

**Comment by abhatikar** [comment] 2016-09-23 15:18
Hi,

I have written an shared library that uses pcap library to capture 802.11 probe requests across different channels and later extract the mac addresses and rssi from the captured packets.

The application links to this library and creates a pthread to call the entry point of the library which setups the capture handle and starts pcap loop to capture the packets

The code organization for the library is as follows

1 setup timer to switch channels every 5 sec

timer_function()
{
            pcap_breakloop()
            pcap_freecode();
            pcap_close(handle)

}
2. setup pcap handle
int32_t pcap_setup_function()
{
            int32_t status = 0;

            /*
            * Create pcap handle
            */

            if((handle = pcap_create(pktcap->dev, pktcap->errbuf)) == NULL)
            {
                        fprintf(stderr, "pcap_create() failed: %s\n", pktcap->errbuf);
                        status = -EFAULT;
                        return status;
            }

            /*
            * Turn off promisc mode
            */

            if(pcap_set_promisc(handle, 0) != 0)
            {
                        fprintf(stderr, "Failed to disable promisc mode.\n");
                        status = -EFAULT;
                        wifi_pcap_close_function();
                        return status;
            }

            /*
            * Set SNAP len
            */

            if(pcap_set_snaplen(handle, BUFSIZ) != 0)
            {
                        fprintf(stderr, "Failed to set snaplen.\n");
                        status = -EFAULT;
                        wifi_pcap_close_function();
                        return status;
            }

            /*
            * Set capture timeout
            */

            if(pcap_set_timeout(handle, 1000) != 0)
            {
                        fprintf(stderr, "Failed to set timeout.\n");
                        status = -EFAULT;
                        wifi_pcap_close_function();
                        return status;
            }

            if(pcap_activate(handle) != 0)
            {
                        fprintf(stderr, "pcap_activate() failed\n");
                        status = -EFAULT;
                        wifi_pcap_close_function();
                        return status;
            }

            /*
            * Compile a filter to sniff 802.11 probe requests
            * wlan type mgt subtype probe-req
            */
            if(pcap_compile(handle, &(pktcap->fp), pktcap->filter_exp, 0, PCAP_NETMASK_UNKNOWN) == -1)
            {
                        fprintf(stderr, "pcap_compile() failed: %s\n", pcap_geterr(handle));
                        status = -EFAULT;
                        wifi_pcap_close_function();
                        return status;
            }

            /*
            * Set the compiled filter
            */
            if(pcap_setfilter(handle, &(pktcap->fp)) == -1)
            {
                        fprintf(stderr, "pcap_setfilter() failed: %s\n", pcap_geterr(handle));
                        status = -EFAULT;
                        pcap_freecode(&pktcap->fp);
                        wifi_pcap_close_function();
                        return status;
            }
            return status;
}

void start_pcap_capture_function(void)
{
            int32_t status = 0;

            /**
            * Setup a timer to strike every scanning interval
            *  to trigger WiFi channel switching.
            */

            status = set_channel_switcher_timer(&oneshotTimer, CHANNEL_SWITCH_SIG, pktcap->interval * 1000);
            if(status != 0)
                        return;

            /**
            * Start the pcap loop to capture and process the WiFi packets
            * loop is broken in the channel_switching_handler before
            * before switching channel
            */
            while((status = pcap_loop(handle, -1, wifi_pcap_process_pkt, NULL)) > 0 );

            timer_delete(oneshotTimer);
}

librarymain()
{
            while(run == 1)
            {
                        pcap_setup_function();
                        start_capture();
            }
} 


The issue is that, the application that links to this library, calls this librarymain() as thread startup function.
int32_t main()
{
            pthread_t hWifi;

            signal(SIGINT, thread_exit);
            
            if(pthread_create(&hWifi, NULL, librarymain, NULL)) {

                        fprintf(stderr, "Error creating thread\n");
                        return 1;
            }

            /* wait for the second thread to finish */
            if(pthread_join(hWifi, NULL)) {

                        fprintf(stderr, "Error joining thread\n");
                        return 2;

            }
            return 0;
}

After a long run for around 12 hours, I hit a segmentation fault in pcap_compile.
Just wanted to know if I am missing something.

Thanks

**Comment by guyharris** [comment] 2016-09-23 18:59
> Just wanted to know if I am missing something.

You're missing the fact that you're describing a completely separate issue from the one @Guinpen is describing.  Please open a separate issue for this, rather than adding your question as a comment on an unrelated issue.

**Comment by guyharris** [comment] 2016-10-03 06:47
The above change, checked into the master branch, appears to have fixed the problem.  (I ended up dding 256MB to `/tmp/bigfile` and scp'ing that file from my Ubuntu guest VM to `/dev/null` on the host in order to generate the traffic to test this, with a somewhat smaller version of the test program that used `eth0` and didn't bother with monitor mode - monitor mode isn't necessary to reproduce the problem.)

**Closed by guyharris** 2016-10-03 06:47 UTC

**Comment by Guinpen** [comment] 2016-10-03 10:09
Thank you for your work.
